version: '3'

services:

  node_api:
    build: .
    ports:
      - "9000:9080" 
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://database:27017/xplorer
      JWT_SECRET: vgsjb92873vsbajhg2348hgcvxvcndg
    depends_on:
      - database

  database:
    image: mongo:7.0.0-rc8-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    restart: always

volumes:
  mongodb: