version: '3'

services:

  node_api:
    build: .
    ports:
      - "9000:8000" 
    environment:
      NODE_ENV: development
      PORT: 9080
      MONGODB_URI: mongodb://mongo_db:27017/xplorer
      JWT_SECRET: vgsjb92873vsbajhg2348hgcvxvcndg
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:20
    ports:
      - "27018:27017"
    volumes:
      - database:/data/db
    restart: always

volumes:
  database: