version: '3'
services:
  server:
    image: Dockerfile
    build: .
    ports:
      - "9080:8000"
    depends_on:
      - 
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
